-- AlterTable
ALTER TABLE "public"."Clients" ADD COLUMN     "address" TEXT,
ADD COLUMN     "contactPerson" TEXT,
ADD COLUMN     "legalName" TEXT,
ADD COLUMN     "pincode" TEXT,
ADD COLUMN     "place" TEXT,
ADD COLUMN     "shippingGstin" TEXT,
ADD COLUMN     "shippingPincode" TEXT,
ADD COLUMN     "shippingState" TEXT,
ADD COLUMN     "shippingStateCode" TEXT,
ADD COLUMN     "stateCode" TEXT;

-- AlterTable
ALTER TABLE "public"."Invoices" ADD COLUMN     "assessableValue" TEXT,
ADD COLUMN     "cgstValue" TEXT,
ADD COLUMN     "dispatchFromAddress" TEXT,
ADD COLUMN     "dispatchFromName" TEXT,
ADD COLUMN     "dispatchFromPincode" TEXT,
ADD COLUMN     "dispatchFromPlace" TEXT,
ADD COLUMN     "documentDate" TIMESTAMP(3),
ADD COLUMN     "documentTypeCode" TEXT NOT NULL DEFAULT 'INV',
ADD COLUMN     "gstRate" TEXT,
ADD COLUMN     "igstValue" TEXT,
ADD COLUMN     "irn" TEXT,
ADD COLUMN     "isService" TEXT,
ADD COLUMN     "items" JSONB,
ADD COLUMN     "placeOfSupplyStateCode" TEXT,
ADD COLUMN     "precedingInvoiceDate" TIMESTAMP(3),
ADD COLUMN     "precedingInvoiceReference" TEXT,
ADD COLUMN     "recipientAddress" TEXT,
ADD COLUMN     "recipientLegalName" TEXT,
ADD COLUMN     "recipientPincode" TEXT,
ADD COLUMN     "recipientPlace" TEXT,
ADD COLUMN     "recipientStateCode" TEXT,
ADD COLUMN     "sgstValue" TEXT,
ADD COLUMN     "shippingToGstin" TEXT,
ADD COLUMN     "shippingToPincode" TEXT,
ADD COLUMN     "shippingToState" TEXT,
ADD COLUMN     "shippingToStateCode" TEXT,
ADD COLUMN     "supplierAddress" TEXT,
ADD COLUMN     "supplierLegalName" TEXT,
ADD COLUMN     "supplierPincode" TEXT,
ADD COLUMN     "supplierPlace" TEXT,
ADD COLUMN     "supplierStateCode" TEXT,
ADD COLUMN     "supplyTypeCode" TEXT;

-- AlterTable
ALTER TABLE "public"."Settings" ADD COLUMN     "defaultDocumentTypeCode" TEXT DEFAULT 'INV',
ADD COLUMN     "defaultIsService" TEXT DEFAULT 'N',
ADD COLUMN     "defaultSupplyTypeCode" TEXT DEFAULT 'B2B',
ADD COLUMN     "dispatchFromAddress" TEXT,
ADD COLUMN     "dispatchFromName" TEXT,
ADD COLUMN     "dispatchFromPincode" TEXT,
ADD COLUMN     "dispatchFromPlace" TEXT,
ADD COLUMN     "supplierAddress" TEXT,
ADD COLUMN     "supplierLegalName" TEXT,
ADD COLUMN     "supplierPincode" TEXT,
ADD COLUMN     "supplierPlace" TEXT,
ADD COLUMN     "supplierStateCode" TEXT;

