export class InvoiceResponseDto {
  id: number;
  invoiceNumber: string;
  invoiceDate: Date;
  dueDate: Date;
  documentTypeCode?: string;
  documentDate?: Date | null;
  precedingInvoiceReference?: string | null;
  precedingInvoiceDate?: Date | null;
  invoiceType: string;
  supplyTypeCode?: string | null;
  isService?: string | null;
  supplierLegalName?: string | null;
  supplierAddress?: string | null;
  supplierPlace?: string | null;
  supplierStateCode?: string | null;
  supplierPincode?: string | null;
  party: string;
  partyGstin: string;
  recipientLegalName?: string | null;
  recipientAddress?: string | null;
  recipientStateCode?: string | null;
  placeOfSupplyStateCode?: string | null;
  recipientPincode?: string | null;
  recipientPlace?: string | null;
  irn?: string | null;
  shippingToGstin?: string | null;
  shippingToState?: string | null;
  shippingToStateCode?: string | null;
  shippingToPincode?: string | null;
  dispatchFromName?: string | null;
  dispatchFromAddress?: string | null;
  dispatchFromPlace?: string | null;
  dispatchFromPincode?: string | null;
  items?: unknown;
  assessableValue?: string | null;
  gstRate?: string | null;
  igstValue?: string | null;
  cgstValue?: string | null;
  sgstValue?: string | null;
  amount?: string | null;
  ewayBillNumber?: string | null;
  transportMode?: string | null;
  notes?: string | null;
  gst?: string | null;
  totalAmount?: string | null;
  status?: string | null;
  createdAt: Date;
  updatedAt: Date;
}
